### ISSUE TITLE
Panel occasionally disappears

### ISSUE THREAD

**Issue by laerm0** [Mark2Mark/Reporter-Toggler#12]
Hi –

For some reason, the panel doesn't load sometimes. I can't seem to find a pattern. At first I thought it was using Glyphs full-screen, but that doesn't appear to be the case.

I'm on Glyphs 2.6.4 (1277), ~OS X~ macOS 10.14.6.

Thanks!

**Comment by laerm0** [comment]
Actually Mark, I don't think this is an issue with your plugin: when Reporter Toggler goes away, other plugins stop working. I think I shall file an issue with Glyphs team.

**Comment by schriftgestalt** [comment]
Is there anything in the macro window when that happens?

**Comment by laerm0** [comment]
I'll keep an eye on it and report back. Thanks Georg.
