### ISSUE TITLE
Needs Glyphs 3 support

### ISSUE THREAD

**Issue by Mark2Mark** [Mark2Mark/Reporter-Toggler#13]
Crashes Glyphs according to user Report.

**However** I have an entirely revamped version 2.0 in the making. Objective-C and nice new features. Considering not update this one, but rather keep it around for Glyphs 2 and publish a new one for Glyphs 3.

**Comment by annie-o** [comment]
Yep, I'm getting those crashes in Glyphs 3, too. Looking forward to the new one, for I keep ReporterToggler open ALL the time -- so handy!

**Comment by schriftgestalt** [comment]
I have updated the binary that most likely has cause the crash.
