### ISSUE TITLE
Access All Reporters in Obj-C

### ISSUE THREAD

**Issue by Mark2Mark** [Mark2Mark/Reporter-Toggler#14]
@schriftgestalt I want to get the list of all existing Reporters. I checked the GSCallbackHandler and can successfully get `GSCallbackHandler.activeReporters`. However the `reporterInstances` is declared as a property and `GSCallbackHandler. reporterInstances` doesn’t work. The python wrapper seems to do the same, why is it not working in Xcode? "Property 'reporterInstances' not found on object of type 'GSCallbackHandler'!"

**Comment by schriftgestalt** [comment]
You have to do `GSCallbackHandler.sharedHandler.reporterInstances` 
(Calling something directly on GSCallbackHandler means that is a class method (it has a `+` at the beginning of method name). But those class methods can’t store stuff as there are no instance variables) 
`sharedHandler` is a singleton

**Comment by Mark2Mark** [comment]
Great. Thank you so much!

Had to remove the dot syntax though to `[[GSCallbackHandler sharedHandler] reporterInstances]` and the dot didn’t work.
(I usually try to go for dots whenever possible)

Hmmm, the compiler is silent, but the console logs `-[GSCallbackHandler reporterInstances]: unrecognized selector sent to instance`. Still no success.

@schriftgestalt one more hint? It’s breaking my head. This looks good to me, but the console still spits that error from above. I really don’t understand. The compiler is happy about the reporterInstances.
```
GSCallbackHandler *handler = [GSCallbackHandler sharedHandler];
MGOrderedDictionary *allReporters = handler.reporterInstances;
```
