### ISSUE TITLE
Not all reporters are showing in G3

### ISSUE THREAD

**Issue by ohbendy** [Mark2Mark/Reporter-Toggler#16]
Hi Mark! Just a note to say that 'mark preview' and 'Speedpunk' are not showing in the reporter toggler for me, though they appear in the View menu

![Screenshot 2022-04-13 at 11 37 53](https://user-images.githubusercontent.com/12471463/163162558-1f3e4f9b-60f5-406e-be3e-cedaf4e92b45.png)

**Comment by ohbendy** [comment]
Wait whoops never mind. I forgot about the Edit part 🙄

**Comment by Mark2Mark** [comment]
No Problem. Glad you found it, hope you still like it 😄
