### ISSUE TITLE
Glyphs 3.2 support?

### ISSUE THREAD

**Issue by sovichet** [Mark2Mark/Reporter-Toggler#17]
I just upgraded to 3.2 and tried to reinstall Reporter-Toggler a few times, but it's still not appearing.

**Comment by Mark2Mark** [comment]
which build number is that please?

Note to self, from the Glyphs Changelog:
```
...
New in Version 3.2 (3173)
2023-01-23
Fix issues with some plugins <<< Maybe related?
...
```

**Comment by sovichet** [comment]
Ahhh. I'm on the build 3175. Maybe it's still fine with 3173?

**Comment by sovichet** [comment]
Ahh. It seems to be fine now. I have no idea why. 🥹

**Comment by Mark2Mark** [comment]
hmmm, weird. But thanks a lot! :)
