### ISSUE TITLE
Suggestion: List sorted alphabeticaly?

### ISSUE THREAD

**Issue by impallari** [Mark2Mark/Reporter-Toggler#2]
Can the list be sorted alphabetically?

**Comment by Mark2Mark** [comment]
Sure, good point! I never checked why the sorting (like the one from the »View« menu) is kinda whack. Thanks! Update should be available in just a bit.

**Comment by Mark2Mark** [comment]
Please let me know if it works.

Should automatically update when you installed it via the Plugin Manager (as you probably know anyway).

**Comment by Mark2Mark** [comment]
There was a bug caused by the new behaviour. I reverted for the moment in order to have the plugin working (but currently not being sorted alphabetically) … To be continued

**Comment by Mark2Mark** [comment]
[Solved]
