### ISSUE TITLE
Glyphs 2.4.x hangs on macOS 10.12.1 when opening any .glyphs file while Glyphs 2.3.1-939 opens them fine because of "Reporter Toggler"

### ISSUE THREAD

**Issue by twardoch** [Mark2Mark/Reporter-Toggler#3]
https://forum.glyphsapp.com/t/glyphs-2-4-x-hangs-on-macos-10-12-1-when-opening-any-glyphs-file-while-glyphs-2-3-1-939-opens-them-fine/5457

**Comment by Mark2Mark** [comment]
Thanks Adam! I don’t have Sierra installed, hence cannot reproduce it.

@schriftgestalt Do you know what’s different with the Glyphs Versions and the OS version?

**Comment by schriftgestalt** [comment]
Can't reproduce it, either. I tested on 10.12.

**Comment by Mark2Mark** [comment]
@twardoch is this still an issue?
