### ISSUE TITLE
ReporterToggler.glyphsPalette slows down Glyphs?

### ISSUE THREAD

**Issue by schriftlabor-miriam** [Mark2Mark/Reporter-Toggler#6]
![screen shot 2018-03-15 at 11 11 02](https://user-images.githubusercontent.com/20683245/37457209-96339aac-2841-11e8-981c-b11c762c0f26.png)

**Comment by Mark2Mark** [comment]
Hehe, Georg is outsourcing the blame to the plugin developers now :)
Thanks for reporting, Miriam.

@schriftgestalt Unfortunately I don’t have the message trigger `from AppKit/Foundation import *` in here, what else causes it? It’s the same with [Kernkraft](https://github.com/bBoxType/Kernkraft).

**Comment by schriftgestalt** [comment]
It might be that the people still have an old version of vanilla.

**Comment by Mark2Mark** [comment]
Ahhhh!

**Comment by rdunk** [comment]
Still seeing this after using Addons > Install Modules to (I assume) update vanilla.
