### ISSUE TITLE
Reporter Toggler not working on MacOS prior 10.12

### ISSUE THREAD

**Issue by fkett** [Mark2Mark/Reporter-Toggler#9]
I encountered a problem with Reporter Toggler not working on MacOS 10.11. It seems that the checkboxWithTitle method, which is used in the plugin, was introduced in AppKit from MacOS 10.12+ (https://developer.apple.com/documentation/appkit/nsbutton/1644525-init).

Would be great if you at least added a note regarding the compatibility.

**Comment by Mark2Mark** [comment]
I thought I added switch to use the according method depending on the OS. I’m currently abroad, so cannot check. I’ve seen @schriftgestalt changed quite a lot. @fkett can you confirm if this is still an issue? Thanks!

**Comment by schriftgestalt** [comment]
The pull request should fix this.

**Comment by fkett** [comment]
Yes, it's working now using the pull request code (on my OSX 10.11). Thanks, @schriftgestalt.

**Comment by Mark2Mark** [comment]
Thanks from me too, @schriftgestalt 🙇
